version: '3'

services:
  dayoffmagnamentdb:
    image: postgres
    container_name: dayoffmagnamentdb
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=dayoffmagnamentdb
    ports: 
    - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgressql/data
    

volumes:
  dbdata: